#!/bin/bash

# define constants
PROJECT_SCRIPTS=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
RUN_DOCKER=$PROJECT_SCRIPTS/run-docker

# load project settings
source $PROJECT_SCRIPTS/.load-project-settings.sh --quiet
if [ $? -ne 0 ]; then
  exit $?
fi

# launch docker container
$RUN_DOCKER --name deputy-$PROJECT_NAME --daemon "bot-procman-deputy --name $PROJECT_NAME-$HOSTNAME"
